name       : valum
version    : 0.3.0
release    : 2
source     :
    - https://github.com/valum-framework/valum/archive/v0.3.0.tar.gz : 6731fb2f2abb6d1bd767b37e7468d78faeb0d0bcdac3d96f8a7f16feda15f473
license    : LGPL-3.0
component  : programming
summary    : Valum is a web micro-framework entirely written in the Vala programming language.
description: |
    Valum is a web micro-framework entirely written in the Vala programming language.
builddeps  :
    - pkgconfig(ctpl)
    - pkgconfig(gee-0.8)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libmarkdown)
    - pkgconfig(libmemcached)
    - pkgconfig(libsoup-2.4)
    - fcgi-devel
    - meson
    - vala
setup      : |
    mkdir build
    cd build
    %meson_configure ..
build      : |
    cd build
    %meson_build
install    : |
    cd build 
    %meson_install
