name       : valum
version    : 0.3.10
release    : 6
source     :
    - https://github.com/valum-framework/valum/archive/v0.3.10.tar.gz : 9a6f127471dd71276ab14772686b811aaed4d9f46882d81306a6c8ee0a574401
license    : LGPL-3.0
component  : programming
libsplit   : no
summary    : Valum is a web micro-framework entirely written in the Vala programming language.
description: |
    Valum is a web micro-framework entirely written in the Vala programming language.
builddeps  :
    - pkgconfig(ctpl)
    - pkgconfig(gee-0.8)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libmarkdown)
    - pkgconfig(libmemcached)
    - pkgconfig(libsoup-2.4)
    - fcgi-devel
    - meson
    - vala
setup      : |
    mkdir build
    cd build
    %meson_configure ..
build      : |
    cd build
    %meson_build
install    : |
    cd build
    %meson_install
