name       : valum
version    : 0.3.8
release    : 5
source     :
    - https://github.com/valum-framework/valum/archive/v0.3.8.tar.gz : f3f9211083da18e59a3bb715ecf3e9d128ad490681c7dcb43535dbfbc6391866
license    : LGPL-3.0
component  : programming
libsplit   : no
summary    : Valum is a web micro-framework entirely written in the Vala programming language.
description: |
    Valum is a web micro-framework entirely written in the Vala programming language.
builddeps  :
    - pkgconfig(ctpl)
    - pkgconfig(gee-0.8)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libmarkdown)
    - pkgconfig(libmemcached)
    - pkgconfig(libsoup-2.4)
    - fcgi-devel
    - meson
    - vala
setup      : |
    mkdir build
    cd build
    %meson_configure ..
build      : |
    cd build
    %meson_build
install    : |
    cd build
    %meson_install
